### ISSUE TITLE
Is it possible to use an image loading library other than Picasso ?

### ISSUE THREAD

**Issue by R4md4c** [halysongoncalves/pugnotification#10]
I'm using UIL in my application, and I don't want to add Picasso as a dependency. 

Perhaps it is a good idea to add an interface for customizing the image loading operations ?

Something like

```
interface ImageLoader {
      public void load(String url, Drawable placeholder, Notification target);
}
```

**Comment by halysongoncalves** [comment]
Hello,

I found very interesting your idea, since not all use the Picasso for image loading. If you want to open a pull request with this change is the will, all work is welcome!

Thank U!

**Comment by R4md4c** [comment]
Hi, I've uploaded a PR #11 . Could you please have a look into it ?

**Comment by halysongoncalves** [comment]
Hello,

I looked at the code today. I will do the pull request by the end of the day!

Thank U!
