### ISSUE TITLE
Custom Sound not playing

### ISSUE THREAD

**Issue by leraptor** [halysongoncalves/pugnotification#23]
I'm using a custom sound and the sound doesn't seem to be playing. It's always defaulting to the default sound.

.sound(Uri.parse("android.resource://" + context.getPackageName() + "/" + R.raw.letter_sent))

**Comment by halysongoncalves** [comment]
Hello,

I will check today which problem is occurring!

Thanks!

**Comment by halysongoncalves** [comment]
Hello,

The problem was solved and already has a new publication (1.6.0) in the central maven. This occurred due to be Notification.DEFAULT_ALL flag set in the class constructor riding notification. This data was removed, but it is now necessary to set one flag, just look at the example.
