### ISSUE TITLE
Can I add FLAG_NO_CLEAR

### ISSUE THREAD

**Issue by sytolk** [halysongoncalves/pugnotification#24]
Can I write this with pugnotification library ?

``` Java
Notification noti = new NotificationCompat.Builder(this).setContentTitle("Title").setSmallIcon(R.drawable.icon).build();
noti.flags |= Notification.FLAG_NO_CLEAR;
nm.notify(MAIN_NOTIFICATION, noti);
```

**Comment by sytolk** [comment]
its have pull request for this issue
https://github.com/halysongoncalves/pugnotification/pull/25

**Comment by halysongoncalves** [comment]
Hello,

First I'm sorry for the delay! library already has a method for this: setDefaults (flags). This method is not meeting your case?

**Comment by halysongoncalves** [comment]
Hi @sytolk 

Managed to check and test the new version?

**Comment by halysongoncalves** [comment]
Hi @sytolk 

By check in version 1.7.0 now available!

**Comment by sytolk** [comment]
Yes with ongoing(true) works now. Thanks!
