### ISSUE TITLE
String Charset

### ISSUE THREAD

**Issue by TunaYagci** [halysongoncalves/pugnotification#26]
@halysongoncalves Is there any way to show native chars? Currently I'm using Turkish letters and they are not displayed correctly.

I've tried URLDecoder.decode("...", charset); but it's not fixing that problem.

**Comment by TunaYagci** [comment]
@halysongoncalves seems like this " wasn't " a problem which occurs only on your library, I've solved this by adding " compileOptions.encoding = 'windows-1254' " to gradle, that solved it.

**Comment by halysongoncalves** [comment]
@MyHeartsECO  Thanks for the report! Any problems or questions just open a report and I'm sorry for the delay in responding!
