### ISSUE TITLE
Buttons not showing in custom notification

### ISSUE THREAD

**Issue by Shailevy** [halysongoncalves/pugnotification#28]
This works fine and show the buttons:
        PugNotification.with(this)
                .load()
                .title(...)
                .message(...)
                .smallIcon(...)
                .largeIcon(..)
                .button(...),
                .button(...)
                .simple()
                .build();

This doesn't:
        PugNotification.with(this)
                .load()
                .title(...)
                .message(...)
                .smallIcon(...)
                .largeIcon(..)
                .button(...),
                .button(...)
                **.custom()**
                .build();

**Comment by halysongoncalves** [comment]
Hi @Shailevy, 

The custom notification has no option to add buttons. Only it can add a background image!
If you have any ideas and want to submit a pull request, be my guest!

**Comment by Shailevy** [comment]
NotificationCompat.Builder supports that so I guess I will use it until the library get more mature :)

**Comment by halysongoncalves** [comment]
Hi @Shailevy 
I'm finishing to implement, and rising to the central maven this new feature!

**Comment by Shailevy** [comment]
1. This still isn't working for me
2. There is a problem in the documentation ( http://www.halysongoncalves.com/Pugnotification/ ) in custom section you call "background" before you call the setImageLoader() which leads to an exception
