### ISSUE TITLE
Handle resource ID in Load.color() properly

### ISSUE THREAD

**Issue by mannodermaus** [halysongoncalves/pugnotification#29]
`Load#color(int)` throws an exception if the provided resource ID is less than or equal to 0. If it isn't, it propagates the input as-is to `NotificationCompat.Builder#setColor(int)`. However, the latter method requires a resolved color, not a color resource ID!

Please handle color resources correctly, just like in `Load#ticket(int)`. I'm proposing to change this:

``` java
public Load color(int color) {
    if (color <= 0) {
        throw new IllegalArgumentException("Resource ID Should Not Be Less Than Or Equal To Zero!");
    }

    this.builder.setColor(color);
    return this;
}
```

to this:

``` java
public Load color(@ColorRes int color) {
    if (color <= 0) {
        throw new IllegalArgumentException("Resource ID Should Not Be Less Than Or Equal To Zero!");
    }

    this.builder.setColor(PugNotification.mSingleton.mContext.getResources().getColor(color));
    return this;
}
```

**Comment by halysongoncalves** [comment]
Merge #33
