### ISSUE TITLE
Image problem: drawable-nodpi\pugnotification_ic_placeholder.png

### ISSUE THREAD

**Issue by hateum** [halysongoncalves/pugnotification#35]
AAPT err(Facade for 1388311168): D:\Test\app\build\intermediates\exploded-aar\com.github.halysongoncalves\pugnotification\1.8.0\res\drawable-nodpi\pugnotification_ic_placeholder.png: libpng warning: iCCP: Not recognizing known sRGB profile that has been edited.

**Comment by hateum** [comment]
it's the first time I use github.
How can I get the project, fix the problem and push it here ?

**Comment by halysongoncalves** [comment]
@hateum Not quite understand your question. Would you like to submit a pull request?

**Comment by hateum** [comment]
I have saved the image with sRGB profile using photoshop and I asked you haw can I pull this

**Comment by halysongoncalves** [comment]
Hi @hateum ,

He could fix the problem?

**Comment by hateum** [comment]
@halysongoncalves  yes, photoshop can do it.
![pugnotification_ic_placeholder](https://cloud.githubusercontent.com/assets/1799019/10790325/ea0382a8-7d82-11e5-8e98-8238d0817c21.png)
