### ISSUE TITLE
Example without Picasso?

### ISSUE THREAD

**Issue by pellyadolfo** [halysongoncalves/pugnotification#36]
hi, I am trying to make this project work but with no luck so far. I tried for hours to do a hello world without Picasso but seems impossible. This is my code:

```
 PugNotification.with(this).load()
            .title("title")
            .message("message")
            .bigTextStyle("bigtext")
            .smallIcon(R.drawable.pugnotification_ic_launcher)
            .largeIcon(R.drawable.pugnotification_ic_launcher)
            .color(android.R.color.background_dark)
            .custom()
            .setImageLoader(new ImageLoader() {
                @Override
                public void load(String uri, OnImageLoadingCompleted onCompleted) {

                }

                @Override
                public void load(int imageResId, OnImageLoadingCompleted onCompleted) {

                }
            })
            .background(R.drawable.pugnotification_ic_launcher)
            .setPlaceholder(R.drawable.pugnotification_ic_placeholder)
            .build();
```

The result of this code is nothing shown after managing to create a dummy class to get rid of the continuous NullPointer. I do not understand why you need 3 images, a small icon, a large icon and a URL.

If you could provide a simpler example without Picasso would be very appreciated. Is this the reason that nothing is shown?

Regards

**Comment by halysongoncalves** [comment]
Hi @pellyadolfo ,

In the very example shows how to use Picasso to display the custom notification with image!
