### ISSUE TITLE
there are no specification or samples for advanced using

### ISSUE THREAD

**Issue by tommyyi** [halysongoncalves/pugnotification#37]
if the user click the notification, i want to do one of the following operations:
1,launch a activity;
2,open a url in the webview or browser outside;
......
how should i do?

i hope there is a sample for every case, thanks so much.

**Comment by halysongoncalves** [comment]
Hi,

Yes there is a way to set the click on the notification to open an Activity. To do this, you need to call the .click () method in the construction of the notification. You can set your own intent pending or leave pugnotification send the default intent.
If you choose the default option, it must define a broadcast receiver to listen to the event:

``` java
ACTION_PUGNOTIFICATION_CLICK_INTENT = "br.com.goncalves.pugnotification.action.click.intent";

ACTION_PUGNOTIFICATION_DIMISS_INTENT = "br.com.goncalves.pugnotification.action.dismiss.intent";
```

An example follows:

``` java
 PugNotification.with(mContext).load()
                            .smallIcon(R.drawable.pugnotification_ic_launcher)
                            .autoCancel(true)
                            .largeIcon(R.drawable.pugnotification_ic_launcher)
                            .title(title)
                            .message(message)
                            .click("Type")
                            .flags(Notification.DEFAULT_ALL);
```
