### ISSUE TITLE
Notification on click listener ?

### ISSUE THREAD

**Issue by vj-1023** [halysongoncalves/pugnotification#40]
@halysongoncalves How dowe set notification's on click event !
The sample code doesn't specify it !

**Comment by halysongoncalves** [comment]
Hi @vj-1023,

I'm sorry for the delay, I was traveling :).

I have an example of click, update tomorrow! But to do this, simply use the method click (), which should pass implementation of PedingIntent or use the default implementation of Pugnotification.
It needs defenir a listener (Broadcast Receiver) in your project, using the actions:

ACTION_PUGNOTIFICATION_CLICK_INTENT = 
"br.com.goncalves.pugnotification.action.click.intent";

ACTION_PUGNOTIFICATION_DIMISS_INTENT = "br.com.goncalves.pugnotification.action.dismiss.intent";

 PugNotification.with(context)
                .load()
                .identifier(++mNotificationCounter)
                .when(System.currentTimeMillis())
                .autoCancel(true)
                .click(NotificationDetailActivity.class, bundle)
                .title(title)
                .message(message)
                .bigTextStyle(message)
                .smallIcon(R.drawable.ic_launcher)
                .largeIcon(R.drawable.ic_launcher)
                .vibrate(new long[]{300, 300})
                .sound(RingtoneManager.getDefaultUri(RingtoneManager.TYPE_NOTIFICATION))
                .simple()
                .build();

**Comment by halysongoncalves** [comment]
Hi @vj-1023 ,

As there was no position, I'm closing the issue!
