### ISSUE TITLE
Notification Progress for indeterminate progress

### ISSUE THREAD

**Issue by GeorgeChackungal** [halysongoncalves/pugnotification#41]
Is there any way to have a progress notification with an indeterminate progress? Something which just says loading  with an google indeterminate progressbar as below?

https://github.com/DreaminginCodeZH/MaterialProgressBar

**Comment by halysongoncalves** [comment]
Hi @GeorgeChackungal,

I'm sorry for the delay, I was traveling :).
Yet there is no such option flag in Pugnotification. The only option is determined progress, which can go updating!

**Comment by halysongoncalves** [comment]
Hi @GeorgeChackungal 

As there was no position, I'm closing the issue!
