### ISSUE TITLE
Vibrate

### ISSUE THREAD

**Issue by aresares** [halysongoncalves/pugnotification#42]
how to use .vibrate(vibrate)

**Comment by halysongoncalves** [comment]
Hi @aresares, you would user:
     .vibrate(new long[]{300, 300})

at the end:
PugNotification.with(context)
                .load()
                .identifier(++mNotificationCounter)
                .when(System.currentTimeMillis())
                .autoCancel(true)
                .click(NotificationDetailActivity.class, bundle)
                .title(title)
                .message(message)
                .bigTextStyle(message)
                .smallIcon(R.drawable.ic_launcher)
                .largeIcon(R.drawable.ic_launcher)
                .vibrate(new long[]{300, 300})
                .sound(RingtoneManager.getDefaultUri(RingtoneManager.TYPE_NOTIFICATION))
                .simple()
                .build();

**Comment by halysongoncalves** [comment]
Hi @aresares ,

As there was no position, I'm closing the issue!
