### ISSUE TITLE
Repeating notification

### ISSUE THREAD

**Issue by RamiTrabelsi** [halysongoncalves/pugnotification#43]
Is there any method to set repeating to the AlarmManager, so the notification can be displayed each week on a specific day for example ?

**Comment by halysongoncalves** [comment]
Hi @RamiTrabelsi ,

There is no method to do this work. I believe this is not a responsibility of it, so you need to implement your code using AlarmManager and call pugnotification!

**Comment by RamiTrabelsi** [comment]
PugNotification is using its own AlarmManager, that doesn't permit us to customize repeating notification.

**Comment by halysongoncalves** [comment]
@RamiTrabelsi ,

Unaware her use AlarmManager own! Tell me know when or local?
