### ISSUE TITLE
start a service on click

### ISSUE THREAD

**Issue by eboye** [halysongoncalves/pugnotification#46]
When passing activity to click it works without an issue, but if I pass an service class to it, it just doesn't fire.

Any ideas?

here's my code:

<pre lang="java"><code>
PugNotification.with(this)
                .load()
                .largeIcon(R.drawable.ic_notif)
                .smallIcon(R.drawable.ic_notif_small)
                .title("Start Service")
                .message("in background")
                .click(MyService.class)
                .simple()
                .build();
</code></pre>

Manifest:

<pre lang="xml" escaped="true"><code>
&lt;service
            android:name=&quot;.MyService&quot;
            android:enabled=&quot;true&quot;
            android:exported=&quot;true&quot;/&gt;
</code></pre>

**Comment by halysongoncalves** [comment]
Hi @eboye,

You want to click on the notification and a service start?

**Comment by halysongoncalves** [comment]
Closing the issue due to no response
