### ISSUE TITLE
Handle notifications

### ISSUE THREAD

**Issue by cbedoy** [halysongoncalves/pugnotification#48]
I have a question:

Is possible handle the notifications, for example if the user touch one notification, open or continue with another process?

I was reading your code, but I can't found how I could handle the notification

:)

**Comment by halysongoncalves** [comment]
Hi @cbedoy ,

It is possible as long as you assign a pendingintent its notification. The pugnotification has several default pendingintent, but you can also create your customized by simply implement PendingIntentNotification.

http://stackoverflow.com/questions/6422319/start-service-from-notification
