### ISSUE TITLE
Use .gitattributes file to normalize the source code commited

### ISSUE THREAD

**Issue by dgomesbr** [halysongoncalves/pugnotification#5]
As we use on https://github.com/jhipster/generator-jhipster/blob/master/.gitattributes to control a few aspects of the committed source code.

Example:
- Contributors on windows may commit files with crlf instead of lf line terminators.

docs: http://git-scm.com/book/en/v2/Customizing-Git-Git-Attributes

**Comment by halysongoncalves** [comment]
@dgomesbr open the codereview
