### ISSUE TITLE
Allow library to load large icon bitmap

### ISSUE THREAD

**Issue by robertoestivill** [halysongoncalves/pugnotification#8]
What do you think about having the library taken care of the bitmap decoding for the large icon ?

I was thinking that maybe you can overload the method, something like the following:

``` java
public class Load {

    // Current method
    public Load largeIcon(Bitmap bitmap ) {
      ...
    }

    // New method
    public Load largeIcon(int largeIcon) {
        if (largeIcon <= 0) {
            throw new IllegalArgumentException("Resource ID Should Not Be Less Than Or Equal To Zero!");
        }
        Bitmap bitmap = BitmapFactory.decodeResource( 
               mNotification.mContext.getResources(), largeIcon )
        this.mBuilder.setLargeIcon(bitmap);
        return this;
    }
```

Would you take a PR for this ?

**Comment by halysongoncalves** [comment]
Hello,

I found it interesting your idea, had not thought of that. If you are interested, open a pull request to change or shall I do?

Anything I am available, hug!

**Comment by robertoestivill** [comment]
I will send you a PR in an hour or so.
Thanks

**Comment by halysongoncalves** [comment]
Thanks you!

**Comment by robertoestivill** [comment]
Please take a look at https://github.com/halysongoncalves/pugnotification/pull/9

Thanks

**Comment by halysongoncalves** [comment]
Hello,

I will raise the new artifact in the central maven and update the references to download!

Thanks for PR!
